
services:
  backend:
    build: ./http-server
    ports: 
      - "8080:8080"
    container_name: int-to-roman-backend
    networks:
      - adobe-project-network
  frontend:
    build: ./frontend-app/react-frontend
    ports:
      - "3000:3000"
    container_name: int-to-roman-frontend
    networks:
      - adobe-project-network
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - adobe-project-network
    restart: unless-stopped
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"  # Maps Grafana to localhost:3001
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true  # Enable anonymous access
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin  # Give full access to anonymous users
      - GF_SECURITY_DISABLE_LOGIN_FORM=true  # Hide the login form
      - GF_DASHBOARD_JSON_PATH=/etc/grafana/provisioning/dashboards
      - GF_SERVER_ENABLE_GRAFANA_WELCOME=false  # Disable welcome page
    volumes:
      - grafana-data:/var/lib/grafana
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./provisioning/dashboards:/etc/grafana/provisioning/dashboards
    networks:
      - adobe-project-network
    restart: unless-stopped

networks:
  adobe-project-network:
    driver: bridge

volumes:
  grafana-data: {}
    

